name: run-deno-executable-tests
description: 'Run Deno executable tests'
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Install Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Behave Tests
      run: |
        deno compile --frozen --unstable-ffi --allow-env --allow-read --allow-write --allow-ffi --allow-net --output functional_tests/executable mod.ts
        cd functional_tests 
        pip3 install -r pip-requirements.txt
        export EXECUTABLE=./executable
        behave
      shell: bash
