name: run-deno-wasm-rust-tests
description: 'Run Rust with WASM exposed as a Deno module Tests'
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Install Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Setup Rust and Deno
      run: |
        rustup default nightly
        cargo install grcov wasm-pack  
        rustup component add llvm-tools-preview
      shell: bash
    - name: Run Rust tests
      run: |
        cargo test
        grcov . --binary-path ./target/debug -s . -t lcov --branch -o ./coverage.lcov
      shell: bash
      env:
        RUSTFLAGS: -Cinstrument-coverage
        LLVM_PROFILE_FILE: "%p-%m.profraw"
    - name: Run Deno tests
      run: |
        wasm-pack build --target web
        deno test -A --coverage=coverage
        deno coverage --exclude=bindings ./coverage --lcov > ./coverage/coverage.lcov
      shell: bash
    - name: Publish Deno Rust coverage report
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.lcov,./coverage/coverage.lcov
