name: release-wasm-rust-library
description: 'Release Wasm Rust library to GitHub and crates.io'
inputs:
  name:
    description: 'Library name'
    required: true
  github-token:
    description: 'Github token'
    required: true
  cargo-registry-token:
    description: 'Crates.io token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.github-token }}
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Perform release
      run: |
        cat <<EOT > .releaserc
        ---
        branches:
          - main
        plugins:
          - - "@semantic-release/commit-analyzer"
            - preset: conventionalcommits
          - - "@semantic-release/release-notes-generator"
            - preset: conventionalcommits
          - - "@semantic-release/exec"
            - verifyConditionsCmd: "semantic-release-rust verify-conditions && wasm-pack build --target web --release && rm pkg/package.json"
              prepareCmd: "semantic-release-rust prepare \${nextRelease.version} && cargo check"
              publishCmd: "cargo publish --no-verify"
          - - "@semantic-release/github"
            - assets:
              - path: pkg/${{ inputs.name }}.js
                name: "${{ inputs.name }}.js"
              - path: pkg/${{ inputs.name }}.d.ts
                name: "${{ inputs.name }}.d.ts"
              - path: pkg/${{ inputs.name }}_bg.wasm
                name: "${{ inputs.name }}_bg.wasm"
              - path: pkg/${{ inputs.name }}_bg.wasm.d.ts
                name: "${{ inputs.name }}_bg.wasm.d.ts"
          - - "@semantic-release/git"
            - assets:
              - Cargo.toml
              - Cargo.lock
          - - "@qiwi/semantic-release-gh-pages-plugin"
            - msg: "release published \${nextRelease.version}"
              src: "pkg"
              dotfiles: true
        EOT
        cargo install semantic-release-rust --version 1.0.0-alpha.8
        cargo install wasm-pack
        npm install --no-save conventional-changelog-conventionalcommits @semantic-release/exec @semantic-release/git @qiwi/semantic-release-gh-pages-plugin
        npx semantic-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        CARGO_REGISTRY_TOKEN: ${{ inputs.cargo-registry-token }}
