name: release-wasm-rust-library
description: 'Release Wasm Rust library to GitHub and publish package to NPM'
inputs:
  scope:
    description: 'Package scope'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Perform release
      run: |
        cargo install semantic-release-rust --version 1.0.0-alpha.8
        cargo install wasm-pack
        wasm-pack build --target web --scope ${{ inputs.scope }} --release
        cat <<EOT > .releaserc
        ---
        branches:
          - main
        plugins:
          - - "@semantic-release/commit-analyzer"
            - preset: conventionalcommits
          - - "@semantic-release/release-notes-generator"
            - preset: conventionalcommits
          - - "@semantic-release/github"
          - - "@semantic-release/npm"
            - pkgRoot: ./pkg
          - - "@semantic-release/exec"
            - verifyConditionsCmd: "semantic-release-rust verify-conditions"
              prepareCmd: "semantic-release-rust prepare \${nextRelease.version}"
              publishCmd: "semantic-release-rust publish"
          - - "@semantic-release/git"
            - assets: Cargo.toml
        EOT
        npm install --no-save conventional-changelog-conventionalcommits @semantic-release/exec @semantic-release/git
        npx semantic-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
