name: release-deno-library
description: 'Release Deno library to GitHub'
inputs:
  token:
    description: 'Github token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Perform release
      run: |
        cat <<EOT >> .releaserc
        ---
        branches:
          - main
        plugins:
          - - "@semantic-release/commit-analyzer"
            - preset: conventionalcommits
          - - "@semantic-release/release-notes-generator"
            - preset: conventionalcommits
          - - "@semantic-release/github"
        EOT
        npm install --no-save conventional-changelog-conventionalcommits
        npx semantic-release
      shell: bash
      working-directory: ./.github/workflows
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
