name: release-deno-library
description: 'Release Deno library to GitHub'
inputs:
  github-token:
    description: 'Github token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Perform release
      run: |
        cat <<EOT > .releaserc
        ---
        branches:
          - main
        plugins:
          - - "@semantic-release/commit-analyzer"
            - preset: conventionalcommits
          - - "@semantic-release/release-notes-generator"
            - preset: conventionalcommits
          - - "@semantic-release/github"
        EOT
        npm install --no-save conventional-changelog-conventionalcommits
        npx semantic-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
