name: generate-rust-docs
description: 'Generate Rust Docs'
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Generate docs
      run: cargo doc
      shell: bash
