name: test-deno-executable
description: 'Test Deno executable'
inputs:
  name:
    description: 'Executable name'
    required: true
  binaries-base-path:
    description: 'Path for binaries output'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        mkdir -p ${{ inputs.binaries-base-path }}
        deno compile --lite --unstable --output ${{ inputs.binaries-base-path }}/${{ inputs.name }} mod.ts
        cd functional_tests 
        pip3 install -r pip-requirements.txt
        export EXECUTABLE=${{ inputs.binaries-base-path }}/${{ inputs.name }}
        behave
      shell: bash
