name: test-deno-executable
description: 'Test Deno executable'
runs:
  using: "composite"
  steps:
    - run: |
        export EXECUTABLE=${{ runner.temp }}/executable
        deno compile --unstable --output ${{ runner.temp }}/executable mod.ts
        cd functional_tests 
        pip3 install -r pip-requirements.txt
        behave
      shell: bash
