name: test-deno-executable
description: 'Test Deno executable'
inputs:
  binary-path:
    description: 'Path for binary output'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        deno compile --lite --unstable --output ${{ inputs.binary-path }} mod.ts
        cd functional_tests 
        pip3 install -r pip-requirements.txt
        export EXECUTABLE=${{ inputs.binary-path }}
        behave
      shell: bash
