name: test-deno-executable
description: 'Test Deno executable'
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Install Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Behave Tests
      run: |
        deno compile --unstable --allow-env --allow-read --allow-write --allow-ffi --allow-net --output functional_tests/executable mod.ts
        cd functional_tests 
        pip3 install -r pip-requirements.txt
        export EXECUTABLE=./executable
        behave
      shell: bash
