name: test-deno-executable
description: 'Test Deno executable'
runs:
  using: "composite"
  steps:
    - run: |
        deno compile --unstable --output functional_tests/executable mod.ts
        cd functional_tests 
        pip3 install -r pip-requirements.txt
        echo "EXECUTABLE=executable" >> $env:GITHUB_ENV
        behave
      shell: bash
