name: test-deno-executable
description: 'Test Deno executable'
runs:
  using: "composite"
  steps:
    - name: Windows Separator
      if: runner.os == 'Windows'
      run: echo "EXECUTABLE=${{ runner.temp }}\executable" >> $env:GITHUB_ENV
      shell: bash
    - name: Non-Windows Separator
      if: runner.os != 'Windows'
      run: echo "EXECUTABLE=${{ runner.temp }}/executable" >> GITHUB_ENV
      shell: bash
    - run: |
        deno compile --unstable --output ${{ env.EXECUTABLE }} mod.ts
        cd functional_tests 
        pip3 install -r pip-requirements.txt
        behave
      shell: bash
