name: release-deno-rust-library
description: 'Release Rust with Deno FFI bindings to GitHub and Crates.io'
inputs:
  name:
    description: 'Library name'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_TO_MAIN_TOKEN }}
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Setup Deno
      run: |
        deno install -Afq -n deno_bindgen https://deno.land/x/deno_bindgen/cli.ts
      shell: bash
    - name: Determine next release version
      id: next_release
      run: |
        cargo install semantic-release-rust --version 1.0.0-alpha.8
        cat <<EOT > .releaserc
        ---
        branches:
          - main
        plugins:
          - - "@semantic-release/commit-analyzer"
            - preset: conventionalcommits
          - - "@semantic-release/exec"
            - verifyReleaseCmd: "::set-output name=version::\${nextRelease.version}"
        EOT
        npm install --no-save conventional-changelog-conventionalcommits @semantic-release/exec
        npx semantic-release -d    
      shell: bash
    - name: Generate Deno FFI Bindings
      if: steps.next_release.outputs.version != ''
      run: |
        deno_bindgen --release https://github.com/${{ env.GITHUB_REPOSITORY }}/releases/tag/v${{ steps.next_release.outputs.version }}
      shell: bash
    - name: Perform release
      run: |
        cargo install semantic-release-rust --version 1.0.0-alpha.8
        cat <<EOT > .releaserc
        ---
        branches:
          - main
        plugins:
          - - "@semantic-release/commit-analyzer"
            - preset: conventionalcommits
          - - "@semantic-release/release-notes-generator"
            - preset: conventionalcommits
          - - "@semantic-release/github"
            - assets:
                - path: ${{ runner.temp }}/target/aarch64-apple-darwin/release/lib${{ inputs.name }}.dylib
                  name: "lib${{ inputs.name }}.dylib"
                - path: ${{ runner.temp }}/target/x86_64-pc-windows-gnu/release/${{ inputs.name }}.dll
                  name: "${{ inputs.name }}.dll"
                - path: ${{ runner.temp }}/target/x86_64-unknown-linux-gnu/release/lib${{ inputs.name }}.so
                  name: "lib${{ inputs.name }}.so"
          - - "@semantic-release/exec"
            - verifyConditionsCmd: "semantic-release-rust verify-conditions"
              prepareCmd: "semantic-release-rust prepare \${nextRelease.version}"
              publishCmd: "semantic-release-rust publish"
          - - "@semantic-release/git"
            - assets: ["Cargo.toml", "bindings/bindings.ts"]
        EOT
        npm install --no-save conventional-changelog-conventionalcommits @semantic-release/exec @semantic-release/git
        npx semantic-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TO_MAIN_TOKEN }}
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
