name: run-wasm-rust-tests
description: 'Run Rust Wasm Tests'
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Run Rust tests
      run: |
        rustup default nightly
        cargo install grcov
        rustup component add llvm-tools-preview
        cargo clean
        cargo test
        grcov . --binary-path ./target/debug -s . -t lcov --branch -o ./coverage.lcov
      shell: bash
      env:
        RUSTFLAGS: -Cinstrument-coverage
        LLVM_PROFILE_FILE: "%p-%m.profraw"
    - name: Publish coverage report
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.lcov
    - name: Run WASM tests
      run: |
        cargo install wasm-pack  
        cargo clean
        wasm-pack test --headless --firefox
      shell: bash
