name: generate-deno-docs
description: 'Generate Deno Docs'
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Install Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Generate docs
      run: deno doc mod.ts
      shell: bash
