name: release-rust-library
description: 'Release Rust library to GitHub and Crates.io'
inputs:
  github-token:
    description: 'Github token'
    required: true
  cargo-registry-token:
    description: 'Crates.io token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Perform release
      run: |
        cargo install semantic-release-rust --version 1.0.0-alpha.8
        cat <<EOT >> .releaserc
        ---
        branches:
          - main
        plugins:
          - - "@semantic-release/commit-analyzer"
            - preset: conventionalcommits
          - - "@semantic-release/release-notes-generator"
            - preset: conventionalcommits
          - "@semantic-release/github"
          - - "@semantic-release/exec"
            - verifyConditionsCmd: "semantic-release-rust verify-conditions"
              prepareCmd: "semantic-release-rust prepare \${nextRelease.version}"
              publishCmd: "semantic-release-rust publish"
        EOT
        npm install --no-save conventional-changelog-conventionalcommits @semantic-release/exec
        npx semantic-release
      shell: bash
      working-directory: ./.github/workflows
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        CARGO_REGISTRY_TOKEN: ${{ inputs.cargo-registry-token }}
