name: release-rust-library
description: 'Release Rust library to GitHub and Crates.io'
inputs:
  github-token:
    description: 'Github token'
    required: true
  cargo-registry-token:
    description: 'Crates.io token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-token }}
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Perform release
      run: |
        cat <<EOT > .releaserc
        ---
        branches:
          - main
        plugins:
          - - "@semantic-release/commit-analyzer"
            - preset: conventionalcommits
          - - "@semantic-release/release-notes-generator"
            - preset: conventionalcommits
          - "@semantic-release/github"
          - - "@semantic-release/exec"
            - verifyConditionsCmd: "semantic-release-rust verify-conditions"
              prepareCmd: "semantic-release-rust prepare \${nextRelease.version}"
              publishCmd: "semantic-release-rust publish"
          - - "@semantic-release/git"
            - assets: 
              - Cargo.toml
        EOT
        cargo install semantic-release-rust --version 1.0.0-alpha.8
        npm install --no-save conventional-changelog-conventionalcommits @semantic-release/exec @semantic-release/git
        npx semantic-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        CARGO_REGISTRY_TOKEN: ${{ inputs.cargo-registry-token }}
