name: release-deno-executable
description: 'Release Deno executable to GitHub'
inputs:
  name:
    description: 'Executable name'
    required: true
  token:
    description: 'Github token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Perform release
      run: |
        zip -j ${{ runner.temp }}/x86_64-pc-windows-msvc/${{ inputs.name }}.zip ${{ runner.temp }}/x86_64-pc-windows-msvc/${{ inputs.name }}.exe
        zip -j ${{ runner.temp }}/x86_64-unknown-linux-gnu/${{ inputs.name }}.zip ${{ runner.temp }}/x86_64-unknown-linux-gnu/${{ inputs.name }}
        zip -j ${{ runner.temp }}/x86_64-apple-darwin/${{ inputs.name }}.zip ${{ runner.temp }}/x86_64-apple-darwin/${{ inputs.name }}
        zip -j ${{ runner.temp }}/aarch64-apple-darwin/${{ inputs.name }}.zip ${{ runner.temp }}/aarch64-apple-darwin/${{ inputs.name }}
        cat <<EOT >> .releaserc
        ---
        branches:
          - main
        plugins:
          - - "@semantic-release/commit-analyzer"
            - preset: conventionalcommits
          - - "@semantic-release/release-notes-generator"
            - preset: conventionalcommits
          - - "@semantic-release/github"
            - assets:
                - path: ${{ runner.temp }}/x86_64-pc-windows-msvc/${{ inputs.name }}.zip
                  name: '${{ inputs.name }}-Windows-\${nextRelease.version}.zip'
                - path: ${{ runner.temp }}/x86_64-unknown-linux-gnu/${{ inputs.name }}.zip
                  name: '${{ inputs.name }}-Linux-\${nextRelease.version}.zip'
                - path: ${{ runner.temp }}/x86_64-apple-darwin/${{ inputs.name }}.zip
                  name: '${{ inputs.name }}-macOS_x86_64-\${nextRelease.version}.zip'
                - path: ${{ runner.temp }}/aarch64-apple-darwin/${{ inputs.name }}.zip
                  name: '${{ inputs.name }}-macOS-\${nextRelease.version}.zip'
        EOT
        npm install conventional-changelog-conventionalcommits
        npx semantic-release
      shell: bash
      working-directory: ./.github/workflows
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
