name: release-deno-executable
description: 'Release Deno executable to GitHub'
inputs:
  name:
    description: 'Executable name'
    required: true
  ouput-path:
    description: 'Path for binaries output'
    required: true
  token:
    description: 'Github token'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        cat <<EOT >> .releaserc
        ---
        branches:
          - main
        plugins:
          - - "@semantic-release/commit-analyzer"
            - preset: conventionalcommits
          - - "@semantic-release/release-notes-generator"
            - preset: conventionalcommits
          - - "@semantic-release/github"
            - assets:
                - path: ${{ inputs.ouput-path }}/x86_64-unknown-linux-gnu/${{ inputs.name }}
                  label: Linux
                - path: ${{ inputs.ouput-path }}/x86_64-pc-windows-msvc/${{ inputs.name }}.exe
                  label: Windows
                - path: ${{ inputs.ouput-path }}/x86_64-apple-darwin/${{ inputs.name }}
                  label: MacOS (Intel)
                - path: ${{ inputs.ouput-path }}/aarch64-apple-darwin/${{ inputs.name }}
                  label: MacOS (Arm)
        EOT
        npm install conventional-changelog-conventionalcommits
        npx semantic-release
      shell: bash
      working-directory: ./.github/workflows
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

