name: cross-compile-deno-executable
description: 'Compile Deno Executable'
inputs:
  binary-path:
    description: 'Path for binary output'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        deno compile --unstable --output ${{ inputs.binary-path }} mod.ts
      shell: bash
