name: compile-deno-executable
description: 'Cross-compile Deno'
inputs:
  name:
    description: 'Executable name'
    required: true
  output-path:
    description: 'Path for binaries output'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        mkdir -p ${{ inputs.output-path }}
        mkdir ${{ inputs.output-path }}/x86_64-pc-windows-msvc
        mkdir ${{ inputs.output-path }}/x86_64-unknown-linux-gnu
        mkdir ${{ inputs.output-path }}/x86_64-apple-darwin
        mkdir ${{ inputs.output-path }}/aarch64-apple-darwin
        deno compile --lite --unstable --target x86_64-pc-windows-msvc --output ${{ inputs.output-path }}/x86_64-pc-windows-msvc/${{ inputs.name }} mod.ts
        deno compile --lite --unstable --target x86_64-unknown-linux-gnu --output ${{ inputs.output-path }}/x86_64-unknown-linux-gnu/${{ inputs.name }} mod.ts
        deno compile --lite --unstable --target x86_64-apple-darwin --output ${{ inputs.output-path }}/x86_64-apple-darwin/${{ inputs.name }} mod.ts
        deno compile --lite --unstable --target aarch64-apple-darwin --output ${{ inputs.output-path }}/aarch64-apple-darwin/${{ inputs.name }} mod.ts
        zip ${{ inputs.output-path }}/x86_64-pc-windows-msvc/${{ inputs.name }}.zip ${{ inputs.output-path }}/x86_64-pc-windows-msvc/${{ inputs.name }}.exe
        zip ${{ inputs.output-path }}/x86_64-unknown-linux-gnu/${{ inputs.name }}.zip ${{ inputs.output-path }}/x86_64-unknown-linux-gnu/${{ inputs.name }}
        zip ${{ inputs.output-path }}/x86_64-apple-darwin/${{ inputs.name }}.zip ${{ inputs.output-path }}/x86_64-apple-darwin/${{ inputs.name }}
        zip ${{ inputs.output-path }}/aarch64-apple-darwin/${{ inputs.name }}.zip ${{ inputs.output-path }}/aarch64-apple-darwin/${{ inputs.name }}
        
      shell: bash
