name: run-deno-tests
description: 'Run Deno Tests'
inputs:
  codecov-token:
    description: 'Codecov token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Install Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - name: Run tests
      run: |
        deno test --allow-read --allow-ffi --allow-env --unstable-ffi --coverage=coverage
        deno coverage ./coverage --lcov > ./coverage/coverage.lcov
      shell: bash
    - name: Publish coverage report
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage/coverage.lcov
      env:
        CODECOV_TOKEN: ${{ inputs.codecov-token }}
