name: run-deno-tests
description: 'Run Deno Tests'
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Install Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Run tests
      run: |
        deno test --allow-read -A --coverage=coverage
        deno coverage ./coverage --lcov > ./coverage/coverage.lcov
      shell: bash
    - name: Publish coverage report
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/coverage.lcov
