name: run-rust-tests
description: 'Run Rust Tests'
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Run tests
      run: |
        rustup default nightly
        cargo clean
        cargo test
      shell: bash
