name: cross-compile-deno-executable
description: 'Cross-compile Deno Executable'
inputs:
  name:
    description: 'Executable name'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Install Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Cross-Compile
      run: |
        mkdir ${{ runner.temp }}/x86_64-pc-windows-msvc
        mkdir ${{ runner.temp }}/x86_64-unknown-linux-gnu
        mkdir ${{ runner.temp }}/aarch64-apple-darwin
        deno compile --unstable --allow-env --allow-read --allow-write --allow-ffi --allow-net --target x86_64-pc-windows-msvc --output ${{ runner.temp }}/x86_64-pc-windows-msvc/${{ inputs.name }} mod.ts
        deno compile --unstable --allow-env --allow-read --allow-write --allow-ffi --allow-net --target x86_64-unknown-linux-gnu --output ${{ runner.temp }}/x86_64-unknown-linux-gnu/${{ inputs.name }} mod.ts
        deno compile --unstable --allow-env --allow-read --allow-write --allow-ffi --allow-net --target aarch64-apple-darwin --output ${{ runner.temp }}/aarch64-apple-darwin/${{ inputs.name }} mod.ts
      shell: bash
