name: release-deno-webapp
description: 'Release Deno webapp to GitHub and GitHub Pages'
inputs:
  name:
    description: 'Webapp name'
    required: true
  github-token:
    description: 'Github token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.github-token }}
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 18
    - name: Install Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Perform release and publish demo
      run: |
        cat <<EOT > .releaserc
        ---
        branches:
          - main
        plugins:
          - - "@semantic-release/commit-analyzer"
            - preset: conventionalcommits
          - - "@semantic-release/release-notes-generator"
            - preset: conventionalcommits
          - - "@semantic-release/exec"
            - prepareCmd: "deno bundle mod.ts html/mod.bundle.js && zip -j ${{ runner.temp }}/${{ inputs.name }}.zip html/* && touch html/.nojekyll"
          - - "@semantic-release/github"
            - assets:
                - path: ${{ runner.temp }}/${{ inputs.name }}.zip
                  name: '${{ inputs.name }}-\${nextRelease.version}.zip'
          - - "@qiwi/semantic-release-gh-pages-plugin"
            - msg: "site published \${nextRelease.version}"
              src: "html"
              dotfiles: true
              add: true
        EOT
        npm install conventional-changelog-conventionalcommits @semantic-release/exec @qiwi/semantic-release-gh-pages-plugin
        npx semantic-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
