name: analyse-rust-code
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  call-analyse-rust-code:
    uses: flowscripter/.github/.github/workflows/analyse-rust-code.yml@v1
    secrets: inherit
