name: analyse-deno-code
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  call-analyse-deno-code:
    uses: flowscripter/.github/workflows/analyse-deno-code.yml@v1
    secrets: inherit
