name: analyse-deno-code
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Analyse Deno Code
        uses: flowscripter/.github/actions/analyse-deno-code@v1
