name: check-deno-dependencies
on:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Update dependencies
        run: deno install -A -f -n udd https://deno.land/x/udd@0.4.1/main.ts && udd deps.ts
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CREATE_PR_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: |
            chore: update dependencies
          branch: update-dependencies
