name: check-rust-dependencies
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'
permissions:
  contents: read
  pull-requests: write
jobs:
  call-check-deno-dependencies:
    uses: flowscripter/.github/.github/workflows/check-rust-dependencies.yml@v1
    secrets: inherit
