name: check-deno-dependencies
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check Deno Dependencies
        uses: flowscripter/.github/actions/check-deno-dependencies@v1
        with:
          pr-token: ${{ secrets.CREATE_PR_TOKEN }}
