name: format-deno-code
on:
  pull_request:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Format Deno Code
        uses: flowscripter/.github/actions/format-deno-code@v1
