name: lint-pr-message
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  call-lint-pr-message:
    uses: flowscripter/.github/workflows/lint-pr-message.yml@v1
    secrets: inherit
