name: lint-pr-message
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.1.0
