name: lint-pr-message
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: flowscripter/.github/actions/lint-pr-message@v1
