name: release-rust-library
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Test Rust
        uses: flowscripter/.github/actions/run-rust-tests@v1
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Release Rust
        uses: flowscripter/.github/actions/release-rust-library@v1
        with:
          github-token: ${{ secrets.PUSH_TO_MAIN_TOKEN }}
          cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
