name: release-deno-executable
on:
  push:
    branches: [main]
jobs:
  call-release-deno-executable:
    uses: flowscripter/.github/.github/workflows/release-deno-executable.yml@v1
    secrets: inherit
