name: release-deno-executable
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Compile Deno
        uses: flowscripter/.github/actions/compile-deno
        with:
          name: deno-template
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Release Deno
        uses: flowscripter/.github/actions/release-deno-executable
        with:
          name: deno-template
