name: release-deno-library
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Test Deno
        uses: flowscripter/.github/actions/run-deno-tests@v1
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Release Deno
        uses: flowscripter/.github/actions/release-deno-library@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
