name: release-deno-webapp
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Deno
        uses: flowscripter/.github/actions/run-deno-tests@v1
  test-deno-webapp:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Test Deno Webapp
        uses: flowscripter/.github/actions/test-deno-webapp@v1
  release:
    runs-on: ubuntu-latest
    needs:
      - test-deno-webapp
    steps:
      - name: Release Deno webapp
        uses: flowscripter/.github/actions/release-deno-webapp@v1
        with:
          name: template-deno-webapp
          github-token: ${{ secrets.COMMIT_TOKEN }}
