name: release-deno-executable
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Test Deno
        uses: flowscripter/.github/actions/run-deno-tests@v1
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
  test-deno-executable:
    runs-on: ${{ matrix.os }}
    needs:
      - test
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Test Deno Executable
        uses: flowscripter/.github/actions/test-deno-executable@v1
  release:
    runs-on: ubuntu-latest
    needs:
      - test-deno-executable
    permissions:
      contents: write
    steps:
      - name: Cross-Compile and Release Deno Executable
        uses: flowscripter/.github/actions/cross-compile-and-release-deno-executable@v1
        with:
          name: template-deno-executable
          github-token: ${{ secrets.GITHUB_TOKEN }}
