name: release-deno-rust-library
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Test Rust and Deno
        uses: flowscripter/.github/actions/run-deno-rust-tests@v1
  release:
    runs-on: macOS-latest
    needs:
      - test
    steps:
      - name: Cross-Compile Rust
        uses: flowscripter/.github/actions/cross-compile-deno-rust-library@v1
        with:
          release: "true"
      - name: Release Deno and Rust
        uses: flowscripter/.github/actions/release-deno-rust-library@v1
        with:
          name: flowscripter_template_deno_rust_library
          github-token: ${{ secrets.PUSH_TO_MAIN_TOKEN }}
          cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
