name: run-deno-docs-and-tests
on:
  pull_request:
    branches: [main]
jobs:
  call-run-deno-docs-and-tests:
    uses: flowscripter/.github/workflows/run-deno-docs-and-tests.yml@v1
    secrets: inherit
