name: run-rust-docs-and-tests
on:
  pull_request:
    branches: [main]
jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Rust Docs
        uses: flowscripter/.github/actions/generate-rust-docs@v1
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Test Rust
        uses: flowscripter/.github/actions/run-rust-tests@v1
