name: test-deno-webapp
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Deno Webapp
        uses: flowscripter/.github/actions/test-deno-webapp@v1
