name: test-deno-executable
on:
  pull_request:
    branches: [main]
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        deno: ["v1.x", "nightly"]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Test Deno Executable
        if: matrix.os == 'windows-latest'
        uses: flowscripter/.github/actions/test-deno-executable@v1.19
        with:
          binary-path: ${{ runner.temp }}\template-deno-executable
      - name: Test Deno Executable
        if: matrix.os != 'windows-latest'
        uses: flowscripter/.github/actions/test-deno-executable@v1.19
        with:
          binary-path: ${{ runner.temp }}/template-deno-executable
