name: run-bun-tests
description: 'Run Bun Tests'
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v6
    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: "latest"
    - name: Install dependencies
      run: bun ci
      shell: bash
    - name: Run tests
      run: bun test
      shell: bash
      if: hashFiles('tests/**') != ''
