name: format-deno-code
description: 'Format Deno Code'
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Install Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - name: Check code format
      run: |
        deno fmt --check mod.ts deps.ts src/ tests/
      shell: bash
