name: generate-deno-docs
description: 'Generate Rust with WASM exposed as a Deno module Docs'
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Install Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Generate docs
      run: cargo install wasm-pack && wasm-pack build --target web && deno doc mod.ts
      shell: bash
