name: test-deno-webapp
description: 'Test Deno webapp'
inputs:
  github-token:
    description: 'Github token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Install Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install Firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: 'latest'
    - name: Install gecko driver
      uses: browser-actions/setup-geckodriver@latest
      with:
        token: ${{ inputs.github-token }}
    - name: Behave Tests
      run: |
        deno bundle mod.ts html/mod.bundle.js
        cd functional_tests 
        pip3 install -r pip-requirements.txt
        behave
      shell: bash
