name: analyse-rust-code
on:
  workflow_call
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Setup and Run Clippy and Cargo Audit
      run: |
        rustup component add clippy
        cargo clippy
        cargo install cargo-audit
        cargo audit
      shell: bash
