name: check-rust-dependencies
on:
  workflow_call
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup cargo and update dependencies
        run: |
          cargo install cargo-edit
          cargo update
          cargo upgrade --incompatible
        shell: bash
      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.CREATE_PR_TOKEN }}
          commit-message: 'fix: update dependencies'
          title: 'fix: update dependencies'
          body: |
            fix: update dependencies
          branch: update-dependencies
      - name: Enable Pull Request Automerge
        if: steps.create-pr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.CREATE_PR_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: squash
