name: format-rust-code
on:
  workflow_call
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Check code format
        run: |
          cargo fmt -- --check
        shell: bash
