name: format-deno-code
on:
  workflow_call
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Check code format
        run: |
          deno fmt --check mod.ts src/ tests/
        shell: bash
