name: lint-pr-message
on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
