name: release-bun-executable
on:
  workflow_call:
    inputs:
      executable-name:
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: false # if not provided codecov will not be run
      NPM_TOKEN:
        required: true
      NPM_GITHUB_TOKEN:
        required: false # to support GitHub hosted Packages  
      PUSH_TO_MAIN_TOKEN:
        required: true
      WINGET_TOKEN:
        required: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Bun Source
        uses: flowscripter/.github/actions/check-bun-source@v1
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          npm-github-token: ${{ secrets.NPM_GITHUB_TOKEN }}
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Run Bun Tests
        uses: flowscripter/.github/actions/run-bun-tests@v1
        with:
          npm-github-token: ${{ secrets.NPM_GITHUB_TOKEN }}
  test-executable:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Run Bun Executable Tests
        uses: flowscripter/.github/actions/run-bun-executable-tests@v1
        with:
          npm-github-token: ${{ secrets.NPM_GITHUB_TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs:
      - check
      - test
      - test-executable
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
      pages: write
      packages: write
    concurrency:
      group: "release"
      cancel-in-progress: false
    outputs:
      tag: ${{ steps.release.outputs.tag }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Bun Install
        run: bun install
        shell: bash
        env:
          NPM_GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
      - name: Perform release
        id: release
        run: |
          cat <<EOT > .releaserc
          ---
          branches:
            - main
          plugins:
            - - "@semantic-release/commit-analyzer"
              - preset: conventionalcommits
            - - "@semantic-release/release-notes-generator"
              - preset: conventionalcommits
            - - "@semantic-release/exec"
              - publishCmd: "echo tag=v\${nextRelease.version} >> $GITHUB_OUTPUT"
            - - "@semantic-release/github"
            - - "@semantic-release/npm"
            - - "@semantic-release/git"
              - assets: 
                - package.json
                - bun.lock
          EOT
          bun add --no-save conventional-changelog-conventionalcommits @semantic-release/exec @semantic-release/git
          bunx semantic-release
        shell: bash
        env:
          GITHUB_ACTION: yes
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PUSH_TO_MAIN_TOKEN }}
  release-linux:
    runs-on: ubuntu-latest
    needs:
      - release
    if: needs.release.outputs.tag != ''
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ needs.release.outputs.tag }}
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Compile Linux
        run: |
          bun install
          bun build index.ts --compile --outfile ${{ inputs.executable-name }} 
          zip -j ${{ inputs.executable-name }}_Linux_x86_64.zip ${{ inputs.executable-name }}
          sha256sum ${{ inputs.executable-name }}_Linux_x86_64.zip | awk '{ print $1 }' > ${{ inputs.executable-name }}_Linux_x86_64.sha256
        shell: bash
        env:
          NPM_GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
      - name: Release Linux
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release.outputs.tag }}
          files: |
            ${{ inputs.executable-name }}_Linux_x86_64.zip
            ${{ inputs.executable-name }}_Linux_x86_64.sha256
  release-windows:
    runs-on: windows-latest
    needs:
      - release
    if: needs.release.outputs.tag != ''
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ needs.release.outputs.tag }}
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Compile Windows
        run: |
          bun install
          bun build index.ts --compile --outfile ${{ inputs.executable-name }} 
        shell: bash
        env:
          NPM_GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
# - name: Sign Windows
#   uses: skymatic/code-sign-action@v1
#   with:
#     certificate: '${{ secrets.WINDOWS_CODESIGN_CERTIFICATE_P12_BASE64 }}'
#     password: '${{ secrets.WINDOWS_CODESIGN_CERTIFICATE_PASSWORD }}'
#     certificatesha1: '${{ secrets.WINDOWS_CODESIGN_CERTIFICATE_SHA1 }}'
#     folder: ${{ runner.temp }}/x86_64-pc-windows-msvc/${{ inputs.executable-name }}.exe
      - name: Zip Windows
        run: |
          7z a ${{ inputs.executable-name }}_Windows_x86_64.zip ${{ inputs.executable-name }}.exe
          sha256sum ${{ inputs.executable-name }}_Windows_x86_64.zip | awk '{ print $1 }' > ${{ inputs.executable-name }}_Windows_x86_64.sha256
        shell: bash
      - name: Release Windows
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release.outputs.tag }}
          files: |
            ${{ inputs.executable-name }}_Windows_x86_64.zip
            ${{ inputs.executable-name }}_Windows_x86_64.sha256
  release-macos:
    runs-on: macos-latest
    needs:
      - release
    if: needs.release.outputs.tag != ''
    permissions:
      contents: write
    outputs:
      sha256: ${{ steps.zip_macos.outputs.sha256 }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ needs.release.outputs.tag }}
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Compile MacOS
        run: |
          bun install
          bun build index.ts --compile --outfile ${{ inputs.executable-name }} 
        shell: bash
        env:
          NPM_GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
# - name: Install App Store Connect API Key
#   run: |
#     mkdir -p private_keys/
#     echo '${{ secrets.APPLE_APP_STORE_CONNECT_KEY_PEM }}' | tr ' ' '\n' > private_keys/AuthKey_${{ secrets.APPLE_APP_STORE_CONNECT_API_KEY_ID }}.p12
#   shell: bash
# - name: Write signing certificate
#   run: |
#     echo '${{ secrets.APPLE_CODESIGN_CERTIFICATE_P12_BASE64 }}' > codesign_cert.p12.base64
#     base64 -d -i codesign_cert.p12.base64 -o codesign_cert.p12
#   shell: bash
# - name: Sign and Notarize
#   uses: indygreg/apple-code-sign-action@v1
#   with:
#     input_path: ${{ runner.temp }}/aarch64-apple-darwin/${{ inputs.executable-name }}
#     notarize: true
#     staple: true
#     p12_file: codesign_cert.p12
#     p12_password: ${{ secrets.APPLE_CODESIGN_CERTIFICATE_PASSWORD }}
#     app_store_connect_api_issuer: ${{ secrets.APPLE_APP_STORE_CONNECT_API_ISSUER_UUID }}
#     app_store_connect_api_key: ${{ secrets.APPLE_APP_STORE_CONNECT_API_KEY_ID }}
      - name: Zip MacOS
        id: zip_macos
        run: |
          zip -j ${{ inputs.executable-name }}_MacOS_aarch64.zip ${{ inputs.executable-name }}
          shasum -a 256 ${{ inputs.executable-name }}_MacOS_aarch64.zip | awk '{ print $1 }' > ${{ inputs.executable-name }}_MacOS_aarch64.sha256
          echo "sha256=$(cat ${{ inputs.executable-name }}_MacOS_aarch64.sha256)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Release MacOS
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release.outputs.tag }}
          files: |
            ${{ inputs.executable-name }}_MacOS_aarch64.zip
            ${{ inputs.executable-name }}_MacOS_aarch64.sha256
  update-brew-formula:
    runs-on: ubuntu-latest
    needs:
      - release
      - release-macos
    if: needs.release.outputs.tag != ''
    permissions:
      contents: write
    steps:
      - name: Update Homebrew Formula
        uses: PanterSoft/update-formula-homebrew-action@master
        with:
          repo: ${{ github.repository}}
          tap: flowscripter/homebrew-tap
          formula: ${{ inputs.executable-name }}.rb  
          download-url: https://github.com/${{ github.repository}}/releases/download/${{ needs.release.outputs.tag }}/${{ inputs.executable-name }}_MacOS_aarch64.zip
          sha256: ${{ needs.release-macos.outputs.sha256 }}
          commit-message: "Update Brew formula for ${{ inputs.executable-name }} to ${{ needs.release.outputs.tag }}"
        env:
          COMMIT_TOKEN: ${{ secrets.PUSH_TO_MAIN_TOKEN }}
  update-winget-pkg:
    runs-on: windows-latest
    needs:
      - release
      - release-windows
    if: needs.release.outputs.tag != ''
    permissions:
      contents: write
    steps:
      - name: Update Winget Package
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Flowscripter.${{ inputs.executable-name }}
          max-versions-to-keep: 5
          token: ${{ secrets.WINGET_TOKEN }}
          release-tag: ${{ needs.release.outputs.tag }}
          installers-regex: _Windows_x86_64\.zip$
