name: release-bun-library
on:
  workflow_call
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Bun Source
        uses: flowscripter/.github/actions/check-bun-source@main
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Run Bun Tests
        uses: flowscripter/.github/actions/run-bun-tests@main
  release:
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Perform release
        run: |
          cat <<EOT > .releaserc
          ---
          branches:
            - main
          plugins:
            - "@semantic-release/commit-analyzer"
              - preset: conventionalcommits
            - "@semantic-release/release-notes-generator"
              - preset: conventionalcommits
            - "@semantic-release/github"
            - "@sebbo2002/semantic-release-jsr"
            - "@semantic-release/npm"
            - "@semantic-release/git"
              - assets: 
                - package.json
          EOT
          npm install --no-save conventional-changelog-conventionalcommits @semantic-release/git @sebbo2002/semantic-release-jsr
          npx semantic-release
        shell: bash
        env:
          GITHUB_ACTION: yes
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PUSH_TO_MAIN_TOKEN }}
