name: release-deno-library
on:
  workflow_call
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Test Deno
        uses: flowscripter/.github/actions/run-deno-tests@v1
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Perform release
        run: |
          cat <<EOT > .releaserc
          ---
          branches:
            - main
          plugins:
            - - "@semantic-release/commit-analyzer"
              - preset: conventionalcommits
            - - "@semantic-release/release-notes-generator"
              - preset: conventionalcommits
            - "@semantic-release/github"
            - - "@sebbo2002/semantic-release-jsr"
            - - "@semantic-release/git"
              - assets: 
                - deno.json
          EOT
          deno install
          npm install --no-save conventional-changelog-conventionalcommits @semantic-release/git @sebbo2002/semantic-release-jsr
          npx semantic-release
        shell: bash
        env:
          GITHUB_ACTION: yes
          GITHUB_TOKEN: ${{ secrets.PUSH_TO_MAIN_TOKEN }}
