name: run-deno-executable-tests
on:
  workflow_call
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-14]
    steps:
      - name: Test Deno Executable
        uses: flowscripter/.github/actions/run-deno-executable-tests@v1
