name: run-deno-docs-and-tests
on:
  workflow_call
jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Rust Docs
        uses: flowscripter/.github/actions/generate-rust-docs@v1
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Test Rust
        uses: flowscripter/.github/actions/run-rust-tests@v1
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
