name: validate-rust-library-pr
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Rust Source
        uses: flowscripter/.github/actions/check-rust-source@v1
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Run Rust Tests
        uses: flowscripter/.github/actions/run-rust-tests@v1
