name: validate-bun-webapp-pr
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false # if not provided codecov will not be run
      NPM_GITHUB_TOKEN:
        required: false # to access GitHub hosted Packages
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Bun Source
        uses: flowscripter/.github/actions/check-bun-source@v1
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          npm-github-token: ${{ secrets.NPM_GITHUB_TOKEN }}
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Run Bun Tests
        uses: flowscripter/.github/actions/run-bun-webapp-tests@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm-github-token: ${{ secrets.NPM_GITHUB_TOKEN }}
